### ISSUE TITLE
More data from get_profile

### ISSUE THREAD

**Issue by Bernhard** [jun85664396/facebook-bot#11]
If you change the facebook graph url for requesting profile attributes to
`https://graph.facebook.com/v2.6/#{@sender_id}?access_token=#{Messenger::Bot::Config.access_token}`
you would get additional data: locale, timezone, gender
(Tested with  https://developers.facebook.com/tools/explorer)
Would that be better in your eyes?

**Comment by cbuchler** [comment]
I think that would be a good idea!

**Comment by jun85664396** [comment]
@Bernhard 
Thanks for your interest. :>
How about this? #12

**Comment by Bernhard** [comment]
@jun85664396 Perfect for me!
