### ISSUE TITLE
Doesn't throw exception on error

### ISSUE THREAD

**Issue by ssnake** [jun85664396/facebook-bot#15]
Faced with silent issue when gem doesn't show why my reply doesn't pass to messenger. Turned out fb messenger returns msg:
`{"error":{"message":"(#100) Length of param message[text] must be less than or equal to 320","type":"OAuthException","code":100,"fbtrace_id":"EqLDMqwyUll"}}`

**Comment by jun85664396** [comment]
The length of the message can't exceed 320.
check the maximum length of message.

**Comment by ssnake** [comment]
It doesn't throw exception....

**Comment by Bernhard** [comment]
@ssnake If you want this feature, why don't you subclass Transmitter and implement this for yourself? Just overwrite the reply method and if the return value indicates an error you throw any exception you want.
