### ISSUE TITLE
Can't differentiate identical posts

### ISSUE THREAD

**Issue by Bernhard** [jun85664396/facebook-bot#16]
Hello!

I ran into a problem: Facebook repeats the sending of the same message, when the server doesn't responds fast enough. Example:

» 24 Jun 2016 13:04:29.310 1077 <190>1 2016-06-24T11:04:28.883542+00:00 app web.1 - - Parameters: {"object"=>"page", "entry"=>[{"id"=>"278485275816386", "time"=>1466766268677, "messaging"=>[{"sender"=>{"id"=>"11489850 ...

» 24 Jun 2016 13:04:39.697 1077 <190>1 2016-06-24T11:04:39.335768+00:00 app web.1 - - Parameters: {"object"=>"page", "entry"=>[{"id"=>"278485275816386", "time"=>1466766279130, "messaging"=>[{"sender"=>{"id"=>"11489850 ...

Identical messages could be identified with entry["id"], which is not available in the called methods.

Any idea how to solve this problem?

**Comment by jun85664396** [comment]
Hello!
Do you check `seq` value?

![image](https://cloud.githubusercontent.com/assets/7875341/16354716/d1d4e140-3ad8-11e6-8aa8-b44e9167af9e.png)
https://developers.facebook.com/docs/messenger-platform/webhook-reference

**Comment by Bernhard** [comment]
Hello! The seq value counts up. In the first request it was 14040 an in the second it was 14043. 
The only value which stays identical is entry["id"].

PS: The requests have images attached and even those urls are different even it's the same photo.
https://scontent.xx.fbcdn.net/v/t35.0-12/XXXXXXX_10153877314488585_200648850_o.jpg?_nc_ad=z-m&oh=f0cc0020e4e7bb428b270351ce7bd76b&oe=576F4E85
https://scontent.xx.fbcdn.net/v/t35.0-12/XXXXXXX_10153877314488585_200648850_o.jpg?_nc_ad=z-m&oh=f0cc0020e4e7bb428b270351ce7bd76b&oe=576F4E85
'X' used for privacy.

**Comment by jun85664396** [comment]
@Bernhard 
Hello! I think seq value check(save each user's seq) is the best way currently.
If you have better idea please share with me.

recipient id is same with entry["id"].

```
Parameters: {"object"=>"page", "entry"=>[{"id"=>"130266200653463", ...........
"recipient" => {"id" => "130266200653463"}.........
```

PS -> because images upload from facebook server. so it return different URL.
