### ISSUE TITLE
Example Link broken. 

### ISSUE THREAD

**Issue by aakashbarot** [jun85664396/facebook-bot#2]
Hey, 
This is great, I have been bombarding stackoverflow with help on this. 

I am new and would love to see an example of the same. 
Thanks a lot. 

P.S: How can I reach Author of this gem? I would love to get some help and would return the favor in the best way possible.

**Comment by jun85664396** [comment]
Hello,
it's Fixed 0ad7075269ea7a62b9a2d1bbe55bb088a6fa7531
I didn't understand the P.S message...
What is mean the reach Author of this gem??
