### ISSUE TITLE
How to setup multiple bots with separate configuration variables?

### ISSUE THREAD

**Issue by echan00** [jun85664396/facebook-bot#22]
What should I do instead if I want to be able to host multiple instances of the same bot? This will be separate bots (using the same code) but with different access tokens, app secret, etc..

**Comment by jun85664396** [comment]
Hi.
this gem is multiple bots configuration not support..

**Comment by iamajvillalobos** [comment]
hi @echan00 have you found a way to do it? I am in the same situation now too.
