### ISSUE TITLE
X-Page-Usage in response header

### ISSUE THREAD

**Issue by sridharraman** [jun85664396/facebook-bot#26]
Hi

As per the Facebook Messenger documentation (https://developers.facebook.com/blog/post/2016/06/16/page-level-rate-limits/), the response header contains additional information:

> The values for call_count, total_cputime and total_time are whole numbers representing the percentage used values for each of the metrics.

Is there any way of accessing these header values using this gem?

Thanks,
Sridhar

**Comment by jun85664396** [comment]
Hi

'X-Page-Usage' is the header used in the Graph API
