### ISSUE TITLE
Not able find access_token validation_token and secret_token

### ISSUE THREAD

**Issue by dinshawr** [jun85664396/facebook-bot#29]
Hello, please let me know from where I will get these 3 token

```
Messenger::Bot.config do |config|
  config.access_token = <PAGE_ACCESS_TOKEN>
  config.validation_token = <VERIFY_TOKEN>
  config.secret_token = <FB_APP_SECRET_TOKEN>
end
```

I had made a facebook developer app 
<img width="994" alt="screen shot 2017-06-21 at 5 52 03 pm" src="https://user-images.githubusercontent.com/15646955/27383873-761462e2-56aa-11e7-8883-39640284176c.png">

please let me know from where I get these tokens.

Thanks in advance!

**Comment by jun85664396** [comment]
Hello
The token can be found here.
![secret](https://user-images.githubusercontent.com/7875341/27521878-53303b9c-5a5c-11e7-8bc3-7367fd3b0df7.png)
FB_APP_SECRET_TOKEN
![page_token](https://user-images.githubusercontent.com/7875341/27521880-5479cb12-5a5c-11e7-9aa6-d037137641d7.png)
PAGE_ACCESS_TOKEN
![verify](https://user-images.githubusercontent.com/7875341/27521882-56493a22-5a5c-11e7-92d8-2724a3478464.png)
VERIFY_TOKEN
Thanks you.
