### ISSUE TITLE
Is there any way to connect to multiple pages through single fb app?

### ISSUE THREAD

**Issue by ravindra9278** [jun85664396/facebook-bot#32]
I have a condition where I need to implement the facebook messenger bot to chat with different business pages, I am not getting any idea how to implement this, could anyone please suggest me is there any way to implement this?

If I will use different pages then, in this case, the PAGE_ACCESS_TOKEN will be different for different pages
```
Messenger::Bot.config do |config|
  config.access_token = <PAGE_ACCESS_TOKEN>
  config.validation_token = <VERIFY_TOKEN>
  config.secret_token = <FB_APP_SECRET_TOKEN>
end
```

**Comment by jun85664396** [comment]
Hello.
messenger-bot-rails do not yet support multiple Facebook pages.
