### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alecrubin** [jun85664396/facebook-bot#5]
After setting up the webhook, what needs to be done to start sending and receiving messages?

**Comment by jun85664396** [comment]
Hello
See https://github.com/jun85664396/messenger-bot-rails/wiki/Getting-Started

**Comment by cbuchler** [comment]
Thanks for this page, @jun85664396! 

Could you add a better description to the delivery method and the postback method?

Best regards

**Comment by jun85664396** [comment]
@cbuchler 
hello.
I have appended description the 'postback' method.
But 'delivery' method has not yet appended.
more description [Messenger Platform](https://developers.facebook.com/docs/messenger-platform/webhook-reference)

**Comment by pierre-pretorius** [comment]
The readme should include an example of sending a message to a user outside the MessengerBotController.  A way to start a conversation with someone.

**Comment by cbuchler** [comment]
@pierre-pretorius just an FYI: Facebook does not allow you to start conversations with new users, however if a user initiated a conversation with you, you can message them

**Comment by jun85664396** [comment]
@pierre-pretorius 
ok I added an example
thanks :>
