### ISSUE TITLE
Sending Structured Messages 

### ISSUE THREAD

**Issue by chetan-guevara** [jun85664396/facebook-bot#6]
Love this Gem! It's been super helpful for me in creating my bot. 
For text it's working really well. 

However, I'm trying to send a structured message to the user and it doesn't seem to be working here. 
Here is my code: 
`response_json = '{
          "attachment": {
            "type": "template",
            "payload": {
              "template_type": "generic",
              "elements": [{
                "title": "First card",
                "subtitle": "Element #1 of an hscroll",
                "image_url": "http://messengerdemo.parseapp.com/img/rift.png",
                "buttons": [{
                  "type": "web_url",
                  "url": "https://www.messenger.com/",
                  "title": "Web url"
                  }, {
                    "type": "postback",
                    "title": "Postback",
                    "payload": "Payload for first element in a generic bubble",
                    }]
              }]}}}'.to_json`

`sender.reply({body: response_json})`

Does anyone know what the issue is here? Is there example code of this working that anyone could share?

**Comment by chetan-guevara** [comment]
Got it working. As a reference for others, my code is included below. Very simple edits: 

`response_json = {
          "attachment": {
            "type": "template",
            "payload": {
              "template_type": "generic",
              "elements": [{
                "title": "First card",
                "subtitle": "Element #1 of an hscroll",
                "image_url": "http://messengerdemo.parseapp.com/img/rift.png",
                "buttons": [{
                  "type": "web_url",
                  "url": "https://www.messenger.com/",
                  "title": "Web url"
                  }, {
                    "type": "postback",
                    "title": "Postback",
                    "payload": "Payload for first element in a generic bubble",
                    }]
              }]}}}`
       `sender.reply(response_json)`

**Comment by jun85664396** [comment]
Hello
I add example in wiki
see https://github.com/jun85664396/messenger-bot-rails/wiki/Example
thanks! :>

**Comment by cbuchler** [comment]
@chetan-guevara out of curiosity, did you use the postBack method, or what to what method did you add your code?

**Comment by chetan-guevara** [comment]
This was added to the 'message' method. But it can be used whenever you use sender.reply(). So this could also be used in the 'postback' method.

**Comment by jun85664396** [comment]
@chetan-guevara @cbuchler
Hi :D
Can we close this issue?
