### ISSUE TITLE
Batching: "entry" can be an array

### ISSUE THREAD

**Issue by Bernhard** [jun85664396/facebook-bot#7]
First of all: Thanks for the gem! 
To me it seems you haven't taken into consideration that "entry" can have multiple elements. (Receiver and Station class.)

"We may batch events in a single callback, especially during moments of high load. Be sure to iterate over entry and messaging in the response to capture all the events sent in the request."
Source: https://developers.facebook.com/docs/messenger-platform/webhook-reference

**Comment by jun85664396** [comment]
Thanks for mention it.
I was misunderstand about entry part.
can review #8
