### ISSUE TITLE
Example for simple user messaging

### ISSUE THREAD

**Issue by cbuchler** [jun85664396/facebook-bot#9]
Hi, 

Would it be able for you to add a simple tutorial on how to message people, simply after you had already a first conversation? 

Thanks!

**Comment by Bernhard** [comment]
@cbuchler You only need the sender id (integer), which you would have to store from the first callback:

```
t = Messenger::Bot::Transmitter.new(947628192019737) #this number won't work for you
t.reply({ text: "Hello, again!" })
```

**Comment by cbuchler** [comment]
@Bernhard thanks for the tip however, I'm a little confused. 

I added the snippet inside a controller, which would be supposed to work but it doesn't. 

However, if I use it inside the rails console, it works perfectly. 

@jun85664396 or @Bernhard any idea why?

**Comment by jun85664396** [comment]
@cbuchler 
Hi
I don't understand.
Can I see the error or code?

**Comment by cbuchler** [comment]
@jun85664396 sure!

Code from my controller: (doesn't work) 

``` ruby
def create
    t = Messenger::Bot::Transmitter.new(params[:recipient_id]) #this number won't work for you
    reply = t.reply({ text: params[:text] })
    logger.info reply
end

Log (for controller code) 
I, [2016-04-29T21:39:01.009751 #27475]  INFO -- : {:ret=>false, :body=>{"error"=>{"message"=>"(#100) No matching user found", "type"=>"OAuthException", "code"=>100, "fbtrace_id"=>"Aki87UWEY6V"}}}

Code from the commandline: (does work) 
Loading development environment (Rails 5.0.0.beta3)
2.3.0 :001 > t = Messenger::Bot::Transmitter.new(1284183328263090)
 => #<Messenger::Bot::Transmitter:0x007fe342627208 @sender_id=1284183328263090> 
2.3.0 :002 > t.reply({text: "Hello World"})
 => {:ret=>true, :body=>{"recipient_id"=>"1284183328263090", "message_id"=>"mid.1461958607066:aa7b557aeb495a5f27"}} 
```

Anything I might have forgotten?

**Comment by jun85664396** [comment]
Parameter data do exist???
or must be authenticated for user

**Comment by cbuchler** [comment]
Of course the params data is filled with form data.

And the user Id I passed, is the user Id I got from messenger when sending
messages via fb to the bot.

**Comment by jun85664396** [comment]
We may suspect 'messenger bot' access token settings.
```ruby
logger.info Messenger::Bot::Config.access_token
```

**Comment by jun85664396** [comment]
@cbuchler  We may suspect messenger bot access token settings.
please check this!!

``` ruby
logger.info Messenger::Bot::Config.access_token
```

**Comment by cbuchler** [comment]
@jun85664396 the access token is properly set when sending via Form.

**Comment by cbuchler** [comment]
@jun85664396 it seems when using the code inside the controller @sender_id is nil 

`#<Messenger::Bot::Transmitter:0x007ffab9647a38 @sender_id=nil>
{:ret=>false, :body=>{"error"=>{"message"=>"(#100) No matching user found", "type"=>"OAuthException", "code"=>100, "fbtrace_id"=>"HkJpV699uf/"}}}`

**Comment by cbuchler** [comment]
Nevermind. Error came from my part!
